/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActorType = "admin" | "api_key" | "system" | "user";

export type ApiKeyKind = "public" | "secret";

export type AirtimeBatchStatus = "completed" | "processing";

export type AirtimeFloatStatus = "empty" | "low" | "ok" | "unknown";

export type AirtimeOrderStatus = "failed" | "pending" | "processing" | "successful";

export type ApiKeyScope = "airtime" | "collections" | "payouts" | "read" | "sms";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type ChannelCapability = "airtime" | "collect" | "payout" | "sms";

export type ChannelHealth = "degraded" | "down" | "healthy";

export type ChannelKind = "airtime" | "bank" | "card" | "mobile_money" | "sms";

export type ChannelStatus = "active" | "disabled" | "maintenance";

export type CheckoutMethod = "card" | "mobile_money";

export type CheckoutSessionStatus = "completed" | "expired" | "open";

export type CollectionStatus = "expired" | "failed" | "pending" | "processing" | "reversed" | "successful";

export type ComplianceReasonCategory = "chargeback_risk" | "fraud_review" | "kyb_review" | "operations" | "other" | "regulatory" | "sanctions_screening";

export type ComplianceReviewStatus = "dismissed" | "open" | "resolved";

export type EmailDeliveryStatus = "failed" | "pending" | "sent";

export type FeeBearer = "customer" | "merchant";

export type FeeMethod = "bank" | "card" | "mobile_money";

export type FeePlanKind = "collection" | "payout" | "sms";

export type FreezeAction = "freeze" | "unfreeze";

export type FreezeType = "collections" | "payouts";

export type FxRateSource = "feed" | "manual";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IdempotencyStatus = "completed" | "in_progress";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type JournalReferenceType = "adjustment" | "airtime" | "collection" | "fee" | "payout" | "reversal" | "settlement" | "sms" | "topup";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type KybDocumentStatus = "approved" | "pending" | "rejected";

export type KybDocumentType = "certificate_of_incorporation" | "director_id" | "other" | "proof_of_address" | "tax_certificate";

export type KybProfileStatus = "approved" | "pending" | "rejected";

export type KybTier = "tier_0" | "tier_1" | "tier_2" | "tier_3";

export type LedgerAccountType = "fx_clearing" | "merchant_airtime_hold" | "merchant_available" | "merchant_payout_hold" | "merchant_pending" | "merchant_reserve" | "platform_fees" | "platform_sms_revenue" | "provider_clearing" | "suspense";

export type MembershipRole = "admin" | "developer" | "finance" | "owner" | "support" | "viewer";

export type MerchantStatus = "active" | "closed" | "pending_kyb" | "suspended";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentLinkAmountMode = "customer_entered" | "fixed";

export type PayoutBatchStatus = "cancelled" | "completed" | "failed" | "on_hold" | "pending_approval" | "processing" | "queued";

export type PayoutStatus = "cancelled" | "failed" | "on_hold" | "pending_approval" | "processing" | "queued" | "reversed" | "successful";

export type PlatformAdminRole = "compliance" | "finance" | "operations" | "super_admin" | "support";

export type PostingDirection = "credit" | "debit";

export type ProviderStatementEntryType = "adjustment" | "collection" | "fee" | "payout";

export type ProviderStatementSource = "api" | "csv_upload";

export type ReconExceptionStatus = "dismissed" | "open" | "resolved";

export type ReconExceptionType = "amount_mismatch" | "missing_at_provider" | "missing_in_richespay" | "status_mismatch";

export type ReconResolutionAction = "dismiss" | "force_status" | "manual_adjustment";

export type RefundStatus = "failed" | "pending" | "processing" | "successful";

export type RpMode = "live" | "test";

export type SenderIdApprovalStatus = "approved" | "pending" | "rejected" | "submitted";

export type SenderIdPurpose = "marketing" | "otp" | "transactional";

export type SettlementAccountType = "bank" | "mobile_money";

export type SmsBatchStatus = "completed" | "partial" | "processing" | "queued";

export type SmsMessageEncoding = "gsm7" | "ucs2";

export type SmsMessageStatus = "delivered" | "failed" | "queued" | "rejected" | "sent" | "undelivered";

export type SmsMessageType = "marketing" | "otp" | "transactional";

export type SmsOtpStatus = "expired" | "failed" | "pending" | "verified";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TopupStatus = "expired" | "failed" | "pending" | "successful";

export interface AirtimeBatches {
  accepted: Generated<number>;
  charge_currency: string;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  failed: Generated<number>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  reference: string | null;
  rejected: Generated<number>;
  rejected_rows: Generated<Json>;
  status: Generated<AirtimeBatchStatus>;
  successful: Generated<number>;
  total_charge: Generated<Int8>;
  total_items: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface AirtimeChannelFloatHistory {
  balance_minor: Int8 | null;
  channel_id: string;
  checked_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  currency: string | null;
  id: string;
  status: AirtimeFloatStatus;
  threshold_minor: Int8;
}

export interface AirtimeChannelFloats {
  balance_minor: Int8 | null;
  channel_id: string;
  checked_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  currency: string | null;
  status: Generated<AirtimeFloatStatus>;
  threshold_minor: Int8;
}

export interface AirtimeDiscountPlans {
  active: Generated<boolean>;
  country_code: string;
  created_at: Generated<Timestamp>;
  discount_bps: number;
  id: string;
  merchant_id: string | null;
  mode: RpMode | null;
  network: string;
  updated_at: Generated<Timestamp>;
}

export interface AirtimeNetworks {
  active: Generated<boolean>;
  country_code: string;
  created_at: Generated<Timestamp>;
  currency: string;
  fixed_denominations: number[] | null;
  max_minor: Int8;
  min_minor: Int8;
  network: string;
  updated_at: Generated<Timestamp>;
}

export interface AirtimeOrders {
  amount: Int8;
  batch_id: string | null;
  channel_id: string | null;
  charge_amount: Int8;
  charge_currency: string;
  completed_at: Timestamp | null;
  country_code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  discount_minor: Generated<Int8>;
  failure_code: string | null;
  fx_rate_id: string | null;
  id: string;
  last_status_check_at: Timestamp | null;
  merchant_id: string;
  metadata: Generated<Json>;
  mode: RpMode;
  network: string;
  next_status_check_at: Timestamp | null;
  phone: string;
  provider_ref: string | null;
  reference: string | null;
  send_attempts: Generated<number>;
  status: Generated<AirtimeOrderStatus>;
  status_check_attempts: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface AccountBalances {
  account_id: string;
  balance: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  version: Generated<Int8>;
}

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  created_by: string;
  expires_at: Timestamp | null;
  id: string;
  ip_allowlist: string[] | null;
  key_hash: string;
  kind: ApiKeyKind;
  last_used_at: Timestamp | null;
  last4: string;
  merchant_id: string;
  mode: RpMode;
  name: string;
  prefix: string;
  revoked_at: Timestamp | null;
  scopes: ArrayType<ApiKeyScope>;
}

export interface ApiRequestLogs {
  api_key_id: string | null;
  created_at: Generated<Timestamp>;
  duration_ms: number;
  ip: string | null;
  merchant_id: string;
  method: string;
  mode: RpMode;
  path: string;
  request_body: Json | null;
  request_id: string;
  response_body: Json | null;
  status_code: number;
}

export interface AuditLogs {
  action: string;
  actor_id: string;
  actor_type: ActorType;
  after: Json | null;
  before: Json | null;
  created_at: Generated<Timestamp>;
  id: string;
  ip: string | null;
  merchant_id: string | null;
  mode: Generated<RpMode>;
  reason: string | null;
  target_id: string | null;
  target_type: string;
  user_agent: string | null;
}

export interface AuthUsers {
  email: string | null;
  id: string;
}

export interface Banks {
  active: Generated<boolean>;
  code: string;
  country_code: string;
  created_at: Generated<Timestamp>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface ChannelHealthEvents {
  channel_id: string;
  created_at: Generated<Timestamp>;
  detail: Json | null;
  from_health: ChannelHealth | null;
  id: string;
  reason: string;
  to_health: ChannelHealth;
}

export interface Channels {
  capabilities: ArrayType<ChannelCapability>;
  config: Generated<Json>;
  country_code: string;
  created_at: Generated<Timestamp>;
  credentials_encrypted: string;
  health: Generated<ChannelHealth>;
  id: string;
  kind: ChannelKind;
  mode: RpMode;
  network: string | null;
  priority: number;
  provider_code: string;
  status: Generated<ChannelStatus>;
  updated_at: Generated<Timestamp>;
}

export interface CheckoutSessions {
  allowed_methods: ArrayType<CheckoutMethod>;
  amount: Int8;
  cancel_url: string | null;
  collection_id: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  customer: Generated<Json>;
  description: string | null;
  expires_at: Timestamp;
  id: string;
  merchant_id: string;
  mode: RpMode;
  payment_link_id: string | null;
  reference: string | null;
  status: Generated<CheckoutSessionStatus>;
  success_url: string | null;
}

export interface Collections {
  amount: Int8;
  card_brand: string | null;
  card_exp_month: number | null;
  card_exp_year: number | null;
  card_last4: string | null;
  channel_id: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: string;
  customer_email: string | null;
  customer_name: string | null;
  description: string | null;
  expires_at: Timestamp | null;
  failure_code: string | null;
  failure_message: string | null;
  fee_bearer: FeeBearer;
  fee_minor: Generated<Int8>;
  fx_rate_id: string | null;
  id: string;
  last_status_check_at: Timestamp | null;
  merchant_id: string;
  metadata: Generated<Json>;
  method: FeeMethod;
  mode: RpMode;
  net_minor: Int8;
  network: string | null;
  next_status_check_at: Timestamp | null;
  phone: string | null;
  presentment_amount: Int8 | null;
  presentment_currency: string | null;
  provider_ref: string | null;
  provider_session: Generated<Json>;
  reference: string | null;
  reference_type: Generated<string>;
  refunded_minor: Generated<Int8>;
  status: CollectionStatus;
  status_check_attempts: Generated<number>;
}

export interface ComplianceReviewFlags {
  created_at: Generated<Timestamp>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  payload: Generated<Json>;
  resource_id: string;
  resource_type: string;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  rule_code: string;
  status: Generated<ComplianceReviewStatus>;
  summary: string;
}

export interface ContactGroupMembers {
  contact_id: string;
  created_at: Generated<Timestamp>;
  group_id: string;
  merchant_id: string;
  mode: RpMode;
}

export interface ContactGroups {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  merchant_id: string;
  mode: RpMode;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Contacts {
  created_at: Generated<Timestamp>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  name: string | null;
  phone: string;
  tags: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface Countries {
  code: string;
  currency: string;
  dial_code: string;
  enabled: Generated<boolean>;
  name: string;
  timezone: string;
}

export interface EmailOutbox {
  body: string;
  created_at: Generated<Timestamp>;
  failure_message: string | null;
  id: string;
  merchant_id: string;
  mode: RpMode;
  recipient_email: string;
  sent_at: Timestamp | null;
  status: Generated<EmailDeliveryStatus>;
  subject: string;
}

export interface EventsOutbox {
  created_at: Generated<Timestamp>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  payload: Json;
  type: string;
}

export interface FeePlans {
  active: Generated<boolean>;
  country_code: string;
  created_at: Generated<Timestamp>;
  currency: string;
  fee_bearer: FeeBearer;
  fixed_minor: Generated<Int8>;
  id: string;
  kind: FeePlanKind;
  max_minor: Int8 | null;
  method: FeeMethod;
  min_minor: Generated<Int8>;
  name: string;
  network: string | null;
  percent_bps: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface FxRates {
  active: Generated<boolean>;
  base: string;
  captured_at: Timestamp;
  created_at: Generated<Timestamp>;
  id: string;
  markup_bps: Generated<number>;
  quote: string;
  rate: Numeric;
  source: FxRateSource;
  updated_at: Generated<Timestamp>;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  merchant_id: string;
  mode: RpMode;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
  status: IdempotencyStatus;
}

export interface Invitations {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  merchant_id: string;
  mode: RpMode;
  role: MembershipRole;
  token_hash: string;
}

export interface JournalEntries {
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  description: string;
  id: string;
  mode: RpMode;
  reference_id: string;
  reference_type: JournalReferenceType;
}

export interface KybDocuments {
  created_at: Generated<Timestamp>;
  document_type: KybDocumentType;
  file_path: string;
  id: string;
  kyb_profile_id: string;
  merchant_id: string;
  mode: RpMode;
  review_note: string | null;
  reviewer_id: string | null;
  status: Generated<KybDocumentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface KybProfiles {
  business_registration_number: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  registered_address: string | null;
  review_note: string | null;
  reviewer_id: string | null;
  status: Generated<KybProfileStatus>;
  tax_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LedgerAccounts {
  channel_id: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  id: string;
  merchant_id: string | null;
  mode: RpMode;
  type: LedgerAccountType;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  merchant_id: string;
  mode: RpMode;
  role: MembershipRole;
  user_id: string;
}

export interface MerchantBalanceAlertThresholds {
  created_at: Generated<Timestamp>;
  currency: string;
  is_below_threshold: Generated<boolean>;
  merchant_id: string;
  mode: RpMode;
  threshold_minor: Int8;
  updated_at: Generated<Timestamp>;
}

export interface MerchantComplianceProfiles {
  airtime_merchant_daily_cap_minor: Int8 | null;
  airtime_number_daily_cap_minor: Int8 | null;
  airtime_velocity_per_number: Generated<number>;
  collections_daily_volume_minor: Int8 | null;
  collections_freeze_category: ComplianceReasonCategory | null;
  collections_max_minor: Generated<Int8>;
  collections_min_minor: Generated<Int8>;
  collections_monthly_volume_minor: Int8 | null;
  contact_link: Generated<string>;
  created_at: Generated<Timestamp>;
  kyb_tier: Generated<KybTier>;
  merchant_id: string;
  mode: RpMode;
  payouts_daily_volume_minor: Int8 | null;
  payouts_freeze_category: ComplianceReasonCategory | null;
  payouts_max_minor: Generated<Int8>;
  payouts_min_minor: Generated<Int8>;
  payouts_monthly_volume_minor: Int8 | null;
  rolling_reserve_bps: Generated<number>;
  rolling_reserve_days: Generated<number>;
  screening_payout_threshold_minor: Int8 | null;
  suspension_category: ComplianceReasonCategory | null;
  suspension_reason: string | null;
  updated_at: Generated<Timestamp>;
  velocity_collections_per_phone: Generated<number>;
  velocity_window_minutes: Generated<number>;
}

export interface MerchantDailyStats {
  collections_amount_minor: Generated<Int8>;
  collections_count: Generated<number>;
  collections_pending_count: Generated<number>;
  collections_successful_count: Generated<number>;
  created_at: Generated<Timestamp>;
  merchant_id: string;
  mode: RpMode;
  payouts_amount_minor: Generated<Int8>;
  payouts_count: Generated<number>;
  payouts_failed_count: Generated<number>;
  payouts_pending_approval_count: Generated<number>;
  payouts_successful_count: Generated<number>;
  sms_count: Generated<number>;
  sms_delivered_count: Generated<number>;
  sms_failed_count: Generated<number>;
  sms_pending_count: Generated<number>;
  sms_spend_minor: Generated<Int8>;
  stat_date: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface MerchantFeeOverrides {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  currency: string;
  fee_bearer: FeeBearer;
  fixed_minor: Generated<Int8>;
  id: string;
  kind: FeePlanKind;
  max_minor: Int8 | null;
  merchant_id: string;
  method: FeeMethod;
  min_minor: Generated<Int8>;
  mode: RpMode;
  name: string;
  network: string | null;
  percent_bps: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface MerchantFreezeHistory {
  action: FreezeAction;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  freeze_type: FreezeType;
  id: string;
  merchant_id: string;
  mode: RpMode;
  reason: string | null;
}

export interface MerchantNotifications {
  body: string;
  created_at: Generated<Timestamp>;
  data: Generated<Json>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  read_at: Timestamp | null;
  title: string;
  type: string;
}

export interface MerchantProducts {
  airtime_enabled: Generated<boolean>;
  airtime_requested: Generated<boolean>;
  collections_enabled: Generated<boolean>;
  collections_requested: Generated<boolean>;
  created_at: Generated<Timestamp>;
  merchant_id: string;
  mode: RpMode;
  payouts_enabled: Generated<boolean>;
  payouts_requested: Generated<boolean>;
  sms_api_enabled: Generated<boolean>;
  sms_broadcast_enabled: Generated<boolean>;
  sms_enabled: Generated<boolean>;
  sms_requested: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface MerchantRollingReserveHolds {
  amount: Int8;
  collection_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  id: string;
  merchant_id: string;
  mode: RpMode;
  release_at: Timestamp;
  released_at: Timestamp | null;
}

export interface Merchants {
  api_rate_limit_rps: Generated<number>;
  collections_freeze_reason: string | null;
  collections_frozen: Generated<boolean>;
  country_code: string;
  created_at: Generated<Timestamp>;
  id: string;
  legal_name: string;
  mode: RpMode;
  payout_approval_threshold_minor: Int8 | null;
  payouts_freeze_reason: string | null;
  payouts_frozen: Generated<boolean>;
  payouts_require_approval: Generated<boolean>;
  settlement_currency: string;
  status: Generated<MerchantStatus>;
  support_email: string | null;
  support_phone: string | null;
  timezone: string;
  topup_transfer_reference: string | null;
  trading_name: string | null;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface MerchantSettlementSettings {
  automatic_daily_settlement_enabled: Generated<boolean>;
  created_at: Generated<Timestamp>;
  last_auto_settlement_for_date: Timestamp | null;
  merchant_id: string;
  mode: RpMode;
  settlement_account_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MsisdnPrefixes {
  country_code: string;
  created_at: Generated<Timestamp>;
  network: string;
  prefix: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentLinks {
  active: Generated<boolean>;
  amount: Int8 | null;
  amount_mode: PaymentLinkAmountMode;
  created_at: Generated<Timestamp>;
  currency: string;
  description: string | null;
  id: string;
  merchant_id: string;
  min_amount: Int8 | null;
  mode: RpMode;
  reusable: Generated<boolean>;
  slug: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface PayoutBatches {
  approved_by: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  id: string;
  item_count: number;
  merchant_id: string;
  metadata: Generated<Json>;
  mode: RpMode;
  reference: string | null;
  status: PayoutBatchStatus;
  total_amount: Int8;
  total_fee_minor: Generated<Int8>;
  total_hold_minor: Int8;
  updated_at: Generated<Timestamp>;
  validation_report: Generated<Json>;
}

export interface Payouts {
  account_name: string | null;
  account_number: string | null;
  amount: Int8;
  approved_by: string | null;
  bank_code: string | null;
  batch_id: string | null;
  channel_id: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  failure_code: string | null;
  failure_message: string | null;
  fee_minor: Generated<Int8>;
  id: string;
  last_status_check_at: Timestamp | null;
  merchant_id: string;
  metadata: Generated<Json>;
  method: FeeMethod;
  mode: RpMode;
  narration: string | null;
  network: string | null;
  next_status_check_at: Timestamp | null;
  phone: string | null;
  provider_ref: string | null;
  reference: string | null;
  send_attempts: Generated<number>;
  status: PayoutStatus;
  status_check_attempts: Generated<number>;
  total_hold_minor: Int8;
}

export interface PlatformAdmins {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  role: PlatformAdminRole;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PlatformSmsSettings {
  created_at: Generated<Timestamp>;
  default_otp_sender_id: string | null;
  mode: RpMode;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Postings {
  account_id: string;
  amount: Int8;
  created_at: Generated<Timestamp>;
  direction: PostingDirection;
  id: string;
  journal_entry_id: string;
}

export interface Profiles {
  created_at: Generated<Timestamp>;
  full_name: string | null;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ProviderApiLogs {
  channel_id: string;
  created_at: Generated<Timestamp>;
  duration_ms: number;
  id: string;
  method: string;
  path: string;
  request_body: Json | null;
  response_body: Json | null;
  status: string;
  status_code: number | null;
}

export interface ProviderCallbacks {
  callback_hash: string;
  channel_id: string;
  headers: Json;
  id: string;
  processed_at: Timestamp | null;
  processing_error: string | null;
  raw_body: string;
  received_at: Generated<Timestamp>;
}

export interface ProviderStatementLines {
  amount: Int8;
  channel_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  entry_type: ProviderStatementEntryType;
  fee_minor: Generated<Int8>;
  id: string;
  provider_ref: string | null;
  provider_status: string | null;
  raw: Generated<Json>;
  statement_date: Timestamp;
  statement_id: string;
}

export interface ProviderStatements {
  channel_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  float_balance_minor: Int8 | null;
  id: string;
  raw_file_path: string;
  source: ProviderStatementSource;
  statement_date: Timestamp;
}

export interface ReconDailySummaries {
  balances_match: Generated<boolean>;
  channel_id: string;
  collection_count: Generated<number>;
  collection_volume: Generated<Int8>;
  created_at: Generated<Timestamp>;
  currency: string;
  exception_count: Generated<number>;
  fee_volume: Generated<Int8>;
  id: string;
  payout_count: Generated<number>;
  payout_volume: Generated<Int8>;
  provider_clearing_balance: Generated<Int8>;
  provider_float_balance: Int8 | null;
  statement_date: Timestamp;
  statement_id: string;
}

export interface ReconExceptions {
  channel_id: string;
  created_at: Generated<Timestamp>;
  currency: string | null;
  exception_type: ReconExceptionType;
  expected_amount: Int8 | null;
  expected_status: string | null;
  id: string;
  merchant_id: string | null;
  mode: RpMode | null;
  provider_amount: Int8 | null;
  provider_ref: string | null;
  provider_status: string | null;
  resolution_action: ReconResolutionAction | null;
  resolution_reason: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  resource_id: string | null;
  resource_type: string | null;
  statement_id: string | null;
  statement_line_id: string | null;
  status: Generated<ReconExceptionStatus>;
}

export interface Refunds {
  amount: Int8;
  channel_id: string | null;
  collection_id: string;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: string;
  failure_code: string | null;
  failure_message: string | null;
  id: string;
  merchant_id: string;
  metadata: Generated<Json>;
  method: FeeMethod;
  mode: RpMode;
  phone: string | null;
  provider_ref: string | null;
  status: RefundStatus;
}

export interface RoutingRules {
  capability: ChannelCapability;
  channel_ids: string[];
  country_code: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: ChannelKind;
  network: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SenderIdApprovals {
  country_code: string;
  created_at: Generated<Timestamp>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  network: string;
  rejection_reason: string | null;
  sender_id_id: string;
  status: Generated<SenderIdApprovalStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface SenderIds {
  authorization_letter: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  merchant_id: string;
  mode: RpMode;
  purpose: SenderIdPurpose;
  sample_message: string;
  sender_id: string;
}

export interface SettlementAccounts {
  cool_off_until: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  details: Generated<Json>;
  id: string;
  is_default: Generated<boolean>;
  merchant_id: string;
  mode: RpMode;
  type: SettlementAccountType;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface SmsBatches {
  accepted_count: Generated<number>;
  body: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  merchant_id: string;
  metadata: Generated<Json>;
  mode: RpMode;
  reference: string | null;
  rejected_count: Generated<number>;
  scheduled_at: Timestamp | null;
  sender_id: string | null;
  status: Generated<SmsBatchStatus>;
  total_count: Generated<number>;
  type: SmsMessageType;
  updated_at: Generated<Timestamp>;
}

export interface SmsMessages {
  batch_id: string | null;
  body: string;
  channel_id: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  delivered_at: Timestamp | null;
  encoding: SmsMessageEncoding;
  failure_code: string | null;
  id: string;
  merchant_id: string;
  metadata: Generated<Json>;
  mode: RpMode;
  price_minor: Int8;
  provider_ref: string | null;
  reference: string | null;
  scheduled_at: Timestamp | null;
  segments: number;
  sender_id: string;
  sent_at: Timestamp | null;
  status: Generated<SmsMessageStatus>;
  to: string;
  type: SmsMessageType;
}

export interface SmsOptOuts {
  created_at: Generated<Timestamp>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  phone: string;
}

export interface SmsOtps {
  attempts: Generated<number>;
  code_hash: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  max_attempts: Generated<number>;
  merchant_id: string;
  mode: RpMode;
  sender_id: string | null;
  sms_message_id: string | null;
  status: Generated<SmsOtpStatus>;
  to: string;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp | null;
}

export interface SmsPrices {
  country_code: string;
  created_at: Generated<Timestamp>;
  currency: string;
  network: string | null;
  price_per_segment_minor: Int8;
  updated_at: Generated<Timestamp>;
}

export interface SmsTemplates {
  body: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  merchant_id: string;
  mode: RpMode;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Topups {
  amount: Int8;
  bank_reference: string | null;
  completed_at: Timestamp | null;
  confirmed_by: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  fee_minor: Generated<Int8>;
  id: string;
  merchant_id: string;
  method: string;
  mode: RpMode;
  provider_ref: string | null;
  source_collection_id: string | null;
  status: TopupStatus;
}

export interface TransactionEvents {
  created_at: Generated<Timestamp>;
  from_status: string | null;
  id: string;
  merchant_id: string;
  mode: RpMode;
  provider_payload: Json | null;
  provider_reference: string | null;
  reason: string | null;
  resource_id: string;
  resource_type: string;
  to_status: string;
}

export interface WebhookDeliveries {
  attempt: number;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  duration_ms: number | null;
  endpoint_id: string;
  event_id: string;
  merchant_id: string;
  mode: RpMode;
  next_retry_at: Timestamp | null;
  response_snippet: string | null;
  status_code: number | null;
}

export interface WebhookEndpoints {
  consecutive_failures: Generated<number>;
  created_at: Generated<Timestamp>;
  description: string;
  enabled: Generated<boolean>;
  events: string[];
  id: string;
  merchant_id: string;
  mode: RpMode;
  secret: string;
  updated_at: Generated<Timestamp>;
  url: string;
}

export interface Withdrawals {
  amount: Int8;
  auto_generated: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  id: string;
  merchant_id: string;
  mode: RpMode;
  payout_id: string;
  settlement_account_id: string;
}

export interface DB {
  account_balances: AccountBalances;
  airtime_batches: AirtimeBatches;
  airtime_channel_float_history: AirtimeChannelFloatHistory;
  airtime_channel_floats: AirtimeChannelFloats;
  airtime_discount_plans: AirtimeDiscountPlans;
  airtime_networks: AirtimeNetworks;
  airtime_orders: AirtimeOrders;
  api_keys: ApiKeys;
  api_request_logs: ApiRequestLogs;
  audit_logs: AuditLogs;
  "auth.users": AuthUsers;
  banks: Banks;
  channel_health_events: ChannelHealthEvents;
  channels: Channels;
  checkout_sessions: CheckoutSessions;
  collections: Collections;
  compliance_review_flags: ComplianceReviewFlags;
  contact_group_members: ContactGroupMembers;
  contact_groups: ContactGroups;
  contacts: Contacts;
  countries: Countries;
  email_outbox: EmailOutbox;
  events_outbox: EventsOutbox;
  fee_plans: FeePlans;
  fx_rates: FxRates;
  idempotency_keys: IdempotencyKeys;
  invitations: Invitations;
  journal_entries: JournalEntries;
  kyb_documents: KybDocuments;
  kyb_profiles: KybProfiles;
  ledger_accounts: LedgerAccounts;
  memberships: Memberships;
  merchant_balance_alert_thresholds: MerchantBalanceAlertThresholds;
  merchant_compliance_profiles: MerchantComplianceProfiles;
  merchant_daily_stats: MerchantDailyStats;
  merchant_fee_overrides: MerchantFeeOverrides;
  merchant_freeze_history: MerchantFreezeHistory;
  merchant_notifications: MerchantNotifications;
  merchant_products: MerchantProducts;
  merchant_rolling_reserve_holds: MerchantRollingReserveHolds;
  merchant_settlement_settings: MerchantSettlementSettings;
  merchants: Merchants;
  msisdn_prefixes: MsisdnPrefixes;
  payment_links: PaymentLinks;
  payout_batches: PayoutBatches;
  payouts: Payouts;
  platform_admins: PlatformAdmins;
  platform_sms_settings: PlatformSmsSettings;
  postings: Postings;
  profiles: Profiles;
  provider_api_logs: ProviderApiLogs;
  provider_callbacks: ProviderCallbacks;
  provider_statement_lines: ProviderStatementLines;
  provider_statements: ProviderStatements;
  recon_daily_summaries: ReconDailySummaries;
  recon_exceptions: ReconExceptions;
  refunds: Refunds;
  routing_rules: RoutingRules;
  sender_id_approvals: SenderIdApprovals;
  sender_ids: SenderIds;
  settlement_accounts: SettlementAccounts;
  sms_batches: SmsBatches;
  sms_messages: SmsMessages;
  sms_opt_outs: SmsOptOuts;
  sms_otps: SmsOtps;
  sms_prices: SmsPrices;
  sms_templates: SmsTemplates;
  topups: Topups;
  transaction_events: TransactionEvents;
  webhook_deliveries: WebhookDeliveries;
  webhook_endpoints: WebhookEndpoints;
  withdrawals: Withdrawals;
}
