/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActorType = "admin" | "api_key" | "system" | "user";

export type ApiKeyKind = "public" | "secret";

export type ApiKeyScope = "collections" | "payouts" | "read" | "sms";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type ChannelCapability = "collect" | "payout" | "sms";

export type ChannelHealth = "degraded" | "down" | "healthy";

export type ChannelKind = "card" | "mobile_money" | "sms";

export type ChannelStatus = "active" | "disabled" | "maintenance";

export type FreezeAction = "freeze" | "unfreeze";

export type FreezeType = "collections" | "payouts";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IdempotencyStatus = "completed" | "in_progress";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type JournalReferenceType = "adjustment" | "collection" | "fee" | "payout" | "reversal" | "settlement" | "sms";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type KybDocumentStatus = "approved" | "pending" | "rejected";

export type KybDocumentType = "certificate_of_incorporation" | "director_id" | "other" | "proof_of_address" | "tax_certificate";

export type KybProfileStatus = "approved" | "pending" | "rejected";

export type LedgerAccountType = "fx_clearing" | "merchant_available" | "merchant_payout_hold" | "merchant_pending" | "merchant_reserve" | "platform_fees" | "platform_sms_revenue" | "provider_clearing" | "suspense";

export type MembershipRole = "admin" | "developer" | "finance" | "owner" | "support" | "viewer";

export type MerchantStatus = "active" | "closed" | "pending_kyb" | "suspended";

export type PlatformAdminRole = "compliance" | "finance" | "operations" | "super_admin" | "support";

export type PostingDirection = "credit" | "debit";

export type RpMode = "live" | "test";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountBalances {
  account_id: string;
  balance: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  version: Generated<Int8>;
}

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  created_by: string;
  expires_at: Timestamp | null;
  id: string;
  ip_allowlist: string[] | null;
  key_hash: string;
  kind: ApiKeyKind;
  last_used_at: Timestamp | null;
  last4: string;
  merchant_id: string;
  mode: RpMode;
  name: string;
  prefix: string;
  revoked_at: Timestamp | null;
  scopes: ArrayType<ApiKeyScope>;
}

export interface ApiRequestLogs {
  api_key_id: string | null;
  created_at: Generated<Timestamp>;
  duration_ms: number;
  ip: string | null;
  merchant_id: string;
  method: string;
  mode: RpMode;
  path: string;
  request_body: Json | null;
  request_id: string;
  response_body: Json | null;
  status_code: number;
}

export interface AuditLogs {
  action: string;
  actor_id: string;
  actor_type: ActorType;
  after: Json | null;
  before: Json | null;
  created_at: Generated<Timestamp>;
  id: string;
  ip: string | null;
  merchant_id: string | null;
  mode: Generated<RpMode>;
  reason: string | null;
  target_id: string | null;
  target_type: string;
  user_agent: string | null;
}

export interface AuthUsers {
  email: string | null;
  id: string;
}

export interface ChannelHealthEvents {
  channel_id: string;
  created_at: Generated<Timestamp>;
  detail: Json | null;
  from_health: ChannelHealth | null;
  id: string;
  reason: string;
  to_health: ChannelHealth;
}

export interface Channels {
  capabilities: ArrayType<ChannelCapability>;
  config: Generated<Json>;
  country_code: string;
  created_at: Generated<Timestamp>;
  credentials_encrypted: string;
  health: Generated<ChannelHealth>;
  id: string;
  kind: ChannelKind;
  mode: RpMode;
  network: string | null;
  priority: number;
  provider_code: string;
  status: Generated<ChannelStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Countries {
  code: string;
  currency: string;
  dial_code: string;
  enabled: Generated<boolean>;
  name: string;
  timezone: string;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  merchant_id: string;
  mode: RpMode;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
  status: IdempotencyStatus;
}

export interface Invitations {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  merchant_id: string;
  mode: RpMode;
  role: MembershipRole;
  token_hash: string;
}

export interface JournalEntries {
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  description: string;
  id: string;
  mode: RpMode;
  reference_id: string;
  reference_type: JournalReferenceType;
}

export interface KybDocuments {
  created_at: Generated<Timestamp>;
  document_type: KybDocumentType;
  file_path: string;
  id: string;
  kyb_profile_id: string;
  merchant_id: string;
  mode: RpMode;
  review_note: string | null;
  reviewer_id: string | null;
  status: Generated<KybDocumentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface KybProfiles {
  business_registration_number: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  merchant_id: string;
  mode: RpMode;
  registered_address: string | null;
  review_note: string | null;
  reviewer_id: string | null;
  status: Generated<KybProfileStatus>;
  tax_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LedgerAccounts {
  channel_id: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  id: string;
  merchant_id: string | null;
  mode: RpMode;
  type: LedgerAccountType;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  merchant_id: string;
  mode: RpMode;
  role: MembershipRole;
  user_id: string;
}

export interface MerchantFreezeHistory {
  action: FreezeAction;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  freeze_type: FreezeType;
  id: string;
  merchant_id: string;
  mode: RpMode;
  reason: string | null;
}

export interface Merchants {
  api_rate_limit_rps: Generated<number>;
  collections_freeze_reason: string | null;
  collections_frozen: Generated<boolean>;
  country_code: string;
  created_at: Generated<Timestamp>;
  id: string;
  legal_name: string;
  mode: RpMode;
  payouts_freeze_reason: string | null;
  payouts_frozen: Generated<boolean>;
  settlement_currency: string;
  status: Generated<MerchantStatus>;
  support_email: string | null;
  support_phone: string | null;
  timezone: string;
  trading_name: string | null;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface MsisdnPrefixes {
  country_code: string;
  created_at: Generated<Timestamp>;
  network: string;
  prefix: string;
  updated_at: Generated<Timestamp>;
}

export interface PlatformAdmins {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  role: PlatformAdminRole;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Postings {
  account_id: string;
  amount: Int8;
  created_at: Generated<Timestamp>;
  direction: PostingDirection;
  id: string;
  journal_entry_id: string;
}

export interface Profiles {
  created_at: Generated<Timestamp>;
  full_name: string | null;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ProviderApiLogs {
  channel_id: string;
  created_at: Generated<Timestamp>;
  duration_ms: number;
  id: string;
  method: string;
  path: string;
  request_body: Json | null;
  response_body: Json | null;
  status: string;
  status_code: number | null;
}

export interface ProviderCallbacks {
  callback_hash: string;
  channel_id: string;
  headers: Json;
  id: string;
  processed_at: Timestamp | null;
  processing_error: string | null;
  raw_body: string;
  received_at: Generated<Timestamp>;
}

export interface RoutingRules {
  capability: ChannelCapability;
  channel_ids: string[];
  country_code: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: ChannelKind;
  network: string | null;
  updated_at: Generated<Timestamp>;
}

export interface TransactionEvents {
  created_at: Generated<Timestamp>;
  from_status: string | null;
  id: string;
  merchant_id: string;
  mode: RpMode;
  provider_payload: Json | null;
  provider_reference: string | null;
  reason: string | null;
  resource_id: string;
  resource_type: string;
  to_status: string;
}

export interface DB {
  account_balances: AccountBalances;
  api_keys: ApiKeys;
  api_request_logs: ApiRequestLogs;
  audit_logs: AuditLogs;
  "auth.users": AuthUsers;
  channel_health_events: ChannelHealthEvents;
  channels: Channels;
  countries: Countries;
  idempotency_keys: IdempotencyKeys;
  invitations: Invitations;
  journal_entries: JournalEntries;
  kyb_documents: KybDocuments;
  kyb_profiles: KybProfiles;
  ledger_accounts: LedgerAccounts;
  memberships: Memberships;
  merchant_freeze_history: MerchantFreezeHistory;
  merchants: Merchants;
  msisdn_prefixes: MsisdnPrefixes;
  platform_admins: PlatformAdmins;
  postings: Postings;
  profiles: Profiles;
  provider_api_logs: ProviderApiLogs;
  provider_callbacks: ProviderCallbacks;
  routing_rules: RoutingRules;
  transaction_events: TransactionEvents;
}
