import type { CurrencyCode } from "@richespay/shared";

import type { Json, PayoutStatus, RpMode, SettlementAccountType } from "../db/types";

export interface SettlementAccountRecord {
  coolOffUntil: Date | null;
  createdAt: Date;
  createdBy: string;
  details: Json;
  id: string;
  isDefault: boolean;
  merchantId: string;
  mode: RpMode;
  type: SettlementAccountType;
  updatedAt: Date;
  updatedBy: string;
  verifiedAt: Date | null;
  verifiedBy: string | null;
}

export interface SettlementSettingsRecord {
  automaticDailySettlementEnabled: boolean;
  createdAt: Date;
  lastAutoSettlementForDate: string | null;
  merchantId: string;
  mode: RpMode;
  settlementAccountId: string | null;
  updatedAt: Date;
}

export interface WithdrawalRecord {
  amount: bigint;
  autoGenerated: boolean;
  createdAt: Date;
  createdBy: string;
  currency: CurrencyCode;
  id: string;
  merchantId: string;
  mode: RpMode;
  payoutId: string;
  settlementAccountId: string;
  status: PayoutStatus;
}
