import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { CollectionService } from "../src/collections";
import { createDatabase, createDatabasePool } from "../src/db/client";
import { startDevPostgres } from "../src/db/dev-postgres";
import { applySqlMigrations } from "../src/db/migrations";
import { runWithSystemScope } from "../src/db/scope";
import { PayoutService } from "../src/payouts";
import { ReconciliationService } from "../src/reconciliation";
import { ProviderCatalog } from "../src/providers/catalog";
import { SettlementService } from "../src/settlements";
import { TopupService } from "../src/topups";

import type { AppDatabase } from "../src/db";
import type { DevPostgresHandle } from "../src/db/dev-postgres";

describe("settlements and reconciliation", () => {
  let collectionService: CollectionService;
  let database: AppDatabase;
  let devPostgres: DevPostgresHandle;
  let payoutService: PayoutService;
  let pool: ReturnType<typeof createDatabasePool>;
  let reconciliationService: ReconciliationService;
  let settlementService: SettlementService;
  let topupService: TopupService;

  beforeAll(async () => {
    devPostgres = await startDevPostgres();
    pool = createDatabasePool(devPostgres.connectionString);
    database = createDatabase(pool);

    await applySqlMigrations(pool);

    const providerCatalog = new ProviderCatalog({
      database,
      encryptionKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    });

    collectionService = new CollectionService({
      database,
      providerCatalog
    });
    payoutService = new PayoutService({
      database,
      providerCatalog
    });
    reconciliationService = new ReconciliationService({
      database,
      payoutService
    });
    settlementService = new SettlementService({
      database,
      payoutService
    });
    topupService = new TopupService({
      database,
      encryptionKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    });

    await runWithSystemScope(
      database,
      "seed settlement and reconciliation tests",
      async (trx) => {
        await trx
          .insertInto("merchants")
          .values([
            {
              collections_frozen: false,
              country_code: "GH",
              id: "mer_settlement_ops",
              legal_name: "Settlement Ops Merchant",
              mode: "test",
              payouts_frozen: false,
              settlement_currency: "GHS",
              status: "active",
              support_email: "ops@merchant.test",
              timezone: "Africa/Accra",
              trading_name: "Settlement Ops Merchant"
            },
            {
              collections_frozen: false,
              country_code: "GH",
              id: "mer_reconciliation_ops",
              legal_name: "Reconciliation Merchant",
              mode: "test",
              payouts_frozen: false,
              settlement_currency: "GHS",
              status: "active",
              support_email: "recon@merchant.test",
              timezone: "Africa/Accra",
              trading_name: "Reconciliation Merchant"
            }
          ])
          .execute();
      },
      { audit: false }
    );
  }, 120000);

  afterAll(async () => {
    if (database || pool) {
      await Promise.allSettled([database?.destroy(), pool?.end()]);
    }

    if (devPostgres) {
      await devPostgres.stop();
    }
  });

  it("requires a verified settlement account and creates manual and automatic withdrawals", async () => {
    await fundMerchant("mer_settlement_ops");

    const account = await settlementService.createAccount({
      createdBy: "finance_user",
      details: {
        account_name: "Ops Settlement",
        network: "mtn_momo",
        phone: "+233241230001"
      },
      isDefault: true,
      merchantId: "mer_settlement_ops",
      mode: "test",
      type: "mobile_money"
    });

    await expect(
      settlementService.createWithdrawal({
        amountMinor: 1000n,
        createdBy: "finance_user",
        currency: "GHS",
        merchantId: "mer_settlement_ops",
        mode: "test",
        requestId: "req_unverified_withdrawal",
        settlementAccountId: account.id
      })
    ).rejects.toThrow(/not yet verified|cool-off/i);

    await settlementService.verifyAccount({
      accountId: account.id,
      adminUserId: "admin_user"
    });
    await clearSettlementCoolOff(account.id);

    const manualWithdrawal = await settlementService.createWithdrawal({
      amountMinor: 1000n,
      createdBy: "finance_user",
      currency: "GHS",
      merchantId: "mer_settlement_ops",
      mode: "test",
      requestId: "req_verified_withdrawal",
      settlementAccountId: account.id
    });

    expect(manualWithdrawal.autoGenerated).toBe(false);
    expect(manualWithdrawal.status).toBe("queued");

    const updatedSettings = await settlementService.updateSettings({
      automaticDailySettlementEnabled: true,
      merchantId: "mer_settlement_ops",
      mode: "test",
      settlementAccountId: account.id
    });

    expect(updatedSettings.automaticDailySettlementEnabled).toBe(true);

    const firstRun = await settlementService.runAutomaticDailySettlements(
      new Date("2026-09-28T10:00:00.000Z")
    );
    const secondRun = await settlementService.runAutomaticDailySettlements(
      new Date("2026-09-28T11:00:00.000Z")
    );

    expect(firstRun).toBe(1);
    expect(secondRun).toBe(0);

    const withdrawals = await settlementService.listWithdrawals(
      "mer_settlement_ops",
      "test",
      10
    );

    expect(withdrawals.some((item) => item.autoGenerated)).toBe(true);
    expect(withdrawals.some((item) => item.id === manualWithdrawal.id)).toBe(true);
  });

  it("imports provider statements with fixture exceptions and resolves them", async () => {
    await fundMerchant("mer_reconciliation_ops");

    const matchingCollection = await collectionService.create({
      amountMinor: 1000n,
      currency: "GHS",
      customerEmail: null,
      customerName: null,
      description: "Matching collection",
      idempotencyKey: null,
      merchantId: "mer_reconciliation_ops",
      metadata: {},
      method: "mobile_money",
      mode: "test",
      network: null,
      phone: "+233241230001",
      reference: "col_match",
      requestId: "req_col_match"
    });
    const statusMismatchCollection = await collectionService.create({
      amountMinor: 1400n,
      currency: "GHS",
      customerEmail: null,
      customerName: null,
      description: "Status mismatch collection",
      idempotencyKey: null,
      merchantId: "mer_reconciliation_ops",
      metadata: {},
      method: "mobile_money",
      mode: "test",
      network: null,
      phone: "+233241230001",
      reference: "col_status_mismatch",
      requestId: "req_col_status_mismatch"
    });

    await collectionService.applyProviderCallback({
      collectionId: matchingCollection.id,
      providerStatus: "successful"
    });

    const amountMismatchPayout = await payoutService.create({
      accountName: null,
      accountNumber: null,
      amountMinor: 900n,
      bankCode: null,
      createdBy: "finance_recon",
      currency: "GHS",
      idempotencyKey: null,
      merchantId: "mer_reconciliation_ops",
      metadata: {},
      method: "mobile_money",
      mode: "test",
      narration: "Amount mismatch payout",
      network: "mtn_momo",
      phone: "+233241230001",
      reference: "pay_amount_mismatch",
      requestId: "req_pay_amount_mismatch"
    });
    const missingAtProviderPayout = await payoutService.create({
      accountName: null,
      accountNumber: null,
      amountMinor: 800n,
      bankCode: null,
      createdBy: "finance_recon",
      currency: "GHS",
      idempotencyKey: null,
      merchantId: "mer_reconciliation_ops",
      metadata: {},
      method: "mobile_money",
      mode: "test",
      narration: "Missing at provider payout",
      network: "mtn_momo",
      phone: "+233241230001",
      reference: "pay_missing_provider",
      requestId: "req_pay_missing_provider"
    });

    const queuedToProcessingAmountMismatchPayout = await payoutService.reconcileProviderConfirmation({
      merchantId: "mer_reconciliation_ops",
      mode: "test",
      now: new Date("2026-09-27T06:55:00.000Z"),
      outcome: "accepted",
      payoutId: amountMismatchPayout.id,
      providerRef: `prov_${amountMismatchPayout.id}`,
      providerStatus: "processing"
    });
    const successfulAmountMismatchPayout = await payoutService.reconcileProviderConfirmation({
      merchantId: "mer_reconciliation_ops",
      mode: "test",
      now: new Date("2026-09-27T07:00:00.000Z"),
      outcome: "succeeded",
      payoutId: queuedToProcessingAmountMismatchPayout.id,
      providerRef:
        queuedToProcessingAmountMismatchPayout.providerRef ?? `prov_${amountMismatchPayout.id}`,
      providerStatus: "successful"
    });
    const processingMissingAtProviderPayout = await payoutService.reconcileProviderConfirmation({
      merchantId: "mer_reconciliation_ops",
      mode: "test",
      now: new Date("2026-09-27T07:03:00.000Z"),
      outcome: "accepted",
      payoutId: missingAtProviderPayout.id,
      providerRef: `prov_${missingAtProviderPayout.id}`,
      providerStatus: "processing"
    });
    const successfulMissingAtProviderPayout = await payoutService.reconcileProviderConfirmation({
      merchantId: "mer_reconciliation_ops",
      mode: "test",
      now: new Date("2026-09-27T07:05:00.000Z"),
      outcome: "succeeded",
      payoutId: processingMissingAtProviderPayout.id,
      providerRef:
        processingMissingAtProviderPayout.providerRef ?? `prov_${missingAtProviderPayout.id}`,
      providerStatus: "successful"
    });

    const imported = await reconciliationService.importStatement({
      channelId: matchingCollection.channelId!,
      currency: "GHS",
      floatBalanceMinor: 0n,
      rawFilePath: "fixtures/provider-statement-2026-09-27.csv",
      rows: [
        {
          amountMinor: matchingCollection.amount,
          currency: "GHS",
          entryType: "collection",
          providerRef: matchingCollection.providerRef,
          providerStatus: "successful",
          raw: { fixture: "matching_collection" }
        },
        {
          amountMinor: statusMismatchCollection.amount,
          currency: "GHS",
          entryType: "collection",
          providerRef: statusMismatchCollection.providerRef,
          providerStatus: "failed",
          raw: { fixture: "status_mismatch" }
        },
        {
          amountMinor: successfulAmountMismatchPayout.amount + 100n,
          currency: "GHS",
          entryType: "payout",
          providerRef: successfulAmountMismatchPayout.providerRef,
          providerStatus: "successful",
          raw: { fixture: "amount_mismatch" }
        },
        {
          amountMinor: 300n,
          currency: "GHS",
          entryType: "payout",
          providerRef: "prov_missing_in_richespay",
          providerStatus: "successful",
          raw: { fixture: "missing_in_richespay" }
        }
      ],
      source: "csv_upload",
      statementDate: "2026-09-27"
    });

    expect(imported.exceptionCount).toBe(4);
    expect(imported.summary.exceptionCount).toBe(4);

    const exceptions = await reconciliationService.listExceptions({
      channelId: matchingCollection.channelId!,
      limit: 10
    });
    const exceptionTypes = exceptions.map((item) => item.exceptionType);
    expect(exceptionTypes).toContain("missing_in_richespay");
    expect(exceptionTypes).toContain("missing_at_provider");
    expect(exceptionTypes).toContain("amount_mismatch");
    expect(exceptionTypes).toContain("status_mismatch");

    const statusMismatchException = exceptions.find(
      (item) => item.exceptionType === "status_mismatch"
    );
    const amountMismatchException = exceptions.find(
      (item) => item.exceptionType === "amount_mismatch"
    );
    expect(statusMismatchException).toBeDefined();
    expect(amountMismatchException).toBeDefined();

    const forced = await reconciliationService.resolveByForceStatus({
      adminUserId: "admin_recon",
      exceptionId: statusMismatchException!.id,
      providerStatus: "failed",
      reason: "Provider confirmed failed settlement"
    });
    expect(forced.status).toBe("resolved");
    expect(forced.resolutionAction).toBe("force_status");

    const adjusted = await reconciliationService.resolveByManualAdjustment({
      adminUserId: "admin_recon",
      amountMinor: 100n,
      creditAccount: {
        channelId: matchingCollection.channelId!,
        merchantId: null,
        type: "provider_clearing"
      },
      currency: "GHS",
      debitAccount: {
        merchantId: null,
        type: "suspense"
      },
      exceptionId: amountMismatchException!.id,
      reason: "Provider fee rounding difference"
    });
    expect(adjusted.status).toBe("resolved");
    expect(adjusted.resolutionAction).toBe("manual_adjustment");

    const payoutAfterForce = await payoutService.getById(
      "mer_reconciliation_ops",
      "test",
      successfulAmountMismatchPayout.id
    );
    expect(payoutAfterForce.status).toBe("successful");

    const collectionAfterForce = await collectionService.getById(
      "mer_reconciliation_ops",
      "test",
      statusMismatchCollection.id
    );
    expect(collectionAfterForce.status).toBe("failed");

    expect(successfulMissingAtProviderPayout.status).toBe("successful");
  });

  async function clearSettlementCoolOff(accountId: string) {
    await runWithSystemScope(
      database,
      "clear settlement cool off",
      async (trx) => {
        await trx
          .updateTable("settlement_accounts")
          .set({
            cool_off_until: new Date("2026-09-26T00:00:00.000Z")
          })
          .where("id", "=", accountId)
          .execute();
      },
      { audit: false }
    );
  }

  async function fundMerchant(merchantId: string) {
    const pendingTopup = await topupService.createBankTransferTopup({
      amountMinor: 20000n,
      currency: "GHS",
      merchantId,
      mode: "test"
    });

    await topupService.confirmBankTransferTopup({
      adminUserId: "admin_seed",
      bankStatementReference: `stmt_${merchantId}_${Date.now()}`,
      reason: "Seed merchant balance",
      topupId: pendingTopup.id
    });
  }
});
